Fix diagnostic for ccall Error message
Before we had
```
error: Expected ')' or ','
ccall((:SetVarDeclInit, libcxxffi), Void, (Ptr{Void},) VD)
                                           ^
```

and were missing the note